unit TestuHTMLWriter;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, SysUtils, uHTMLWriter, HTMLWriterUtils;

type
  // Test methods for class THTMLWriter

  TestTHTMLWriter = class(TTestCase)
  strict private
    FHTMLWriter: THTMLWriter;
    function HTMLWriterFactory(aTagName: string): THTMLWriter;
    function HTML(aString: string): string;
  private

  public
    procedure SetUp; override;
    procedure TearDown; override;

  published

    procedure TestCloseComment;
    procedure TestAddTitle;
    procedure TestTHTMLWidth1;
    procedure TestTHTMLWidth2;
    procedure TestAddBase;
    procedure TestNonHTMLTag;
    procedure TestCreateDocument;

    procedure TestFieldSetAndLegend;

    procedure TestOpenForm;
    procedure TestOpenIFrame;
    procedure TestAddIFrame;

    procedure TestAddAcronymText;
    procedure TestAddAbbreviationText;
    procedure TestAddAddressText;
    procedure TestAddBDOText;
    procedure TestAddBigText;
    procedure TestAddCenterText;
    procedure TestAddCodeText;
    procedure TestAddDeleteText;
    procedure TestAddDefinitionText;
    procedure TestAddFontText;
    procedure TestAddKeyboardText;
    procedure TestAddQuotationText;
    procedure TestAddSampleText;
    procedure TestAddSmallText;
    procedure TestAddStrikeText;
    procedure TestAddTeletypeText;
    procedure TestAddVariableText;

    procedure TestOpenAcronym;
    procedure TestOpenAbbreviation;
    procedure TestOpenAddress;
    procedure TestOpenBDO;
    procedure TestOpenBig;
    procedure TestOpenCenter;
    procedure TestOpenCode;
    procedure TestOpenDelete;
    procedure TestOpenDefinition;
    procedure TestOpenFont;
    procedure TestOpenKeyboard;
    procedure TestOpenQuotation;
    procedure TestOpenSample;
    procedure TestOpenSmall;
    procedure TestOpenStrike;
    procedure TestOpenTeletype;
    procedure TestOpenVariable;

    procedure TestLoadSave;
    procedure TestOpenScript;
    procedure TestAddScript;
    procedure TestConstructorException;
    procedure TestThatExceptionsAreRaised;

    procedure TestAddTableData;
    procedure TestAddLineBreak;
    procedure TestOpenListItem;
    procedure TestAddListItem;
    procedure TestAddHardRule;
    procedure TestAddSpanTextWithStyle;
    procedure TestAddDivTextWithStyle;
    procedure TestAddSpanTextWithID;
    procedure TestAddDivTextWithID;
    procedure TestOpenComment;
    procedure TestAddMetaNamedContent;
    procedure TestAddComment;
    procedure TestAsHTML;
    procedure TestAddText;
    procedure TestAddHead;
    procedure TestOpenTitle;

    procedure TestOpenBody;
    procedure TestOpenTable;
    procedure TestOpenTableRow;
    procedure TestOpenTableData;
    procedure TestOpenImage;
    procedure TestAddImage;
    procedure TestOpenMeta;
    procedure TestOpenAnchor;
    procedure TestAddAnchor;
    procedure TestOpenParagraph;
    procedure TestOpenParagraphWithStyle;
    procedure TestOpenParagraphWithID;
    procedure TestAddParagraphTextWithStyle;
    procedure TestAddParagraphTextWithID;
    procedure TestOpenSpan;
    procedure TestOpenDiv;
    procedure TestOpenBlockQuote;
    procedure TestOpenUnorderedList;
    procedure TestOpenOrderedList;
    procedure TestAddParagraphText;
    procedure TestAddSpanText;
    procedure TestAddDivText;
    procedure TestAddBlockQuoteText;
    procedure TestOpenBold;
    procedure TestOpenItalic;
    procedure TestOpenUnderline;
    procedure TestOpenEmphasis;
    procedure TestOpenStrong;
    procedure TestOpenPre;
    procedure TestOpenCite;
    procedure TestAddBoldText;
    procedure TestAddItalicText;
    procedure TestAddUnderlinedText;
    procedure TestAddEmphasisText;
    procedure TestAddStrongText;
    procedure TestAddPreformattedText;
    procedure TestAddCitationText;
    procedure TestOpenHeading1;
    procedure TestOpenHeading2;
    procedure TestOpenHeading3;
    procedure TestOpenHeading4;
    procedure TestOpenHeading5;
    procedure TestOpenHeading6;
    procedure TestAddHeading1Text;
    procedure TestAddHeading2Text;
    procedure TestAddHeading3Text;
    procedure TestAddHeading4Text;
    procedure TestAddHeading5Text;
    procedure TestAddHeading6Text;
    procedure TestAddStyle;
    procedure TestAddClass;
    procedure TestAddID;
    procedure TestAddAttribute;
    procedure TestCloseTag;
  end;
  // Test methods for class IGetHTML

  TestIGetHTML = class(TTestCase)
  strict private
    FIGetHTML: IGetHTML;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAsHTML;
  end;

implementation

uses Windows;

procedure TestTHTMLWriter.SetUp;
begin
  FHTMLWriter := nil;
end;

procedure TestTHTMLWriter.TearDown;
begin

end;

procedure TestTHTMLWriter.TestAsHTML;
begin
  // This gets tested so much below, and it is so simple, that we don't
  // really need much testing here....

  CheckEquals('<html></html>', HTMLWriterFactory('html').CloseTag.AsHTML);
end;

procedure TestTHTMLWriter.TestAddTeletypeText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftTeletype];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddTeletypeText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddTeletypeText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddText;
var
  aString: string;
  ExpectedValue: string;
  Result: string;
begin
  aString := 'this';
  ExpectedValue := HTML(aString); // '<html>this</html>';
  FHTMLWriter := HTMLWriterFactory('html');
  FHTMLWriter.AddText(aString);
  Result := FHTMLWriter.CloseTag.AsHTML;
  CheckEquals(ExpectedValue, Result);

  // arbitrary tags
  aString := 'this';
  ExpectedValue := Format('<%s>%s</%s>', [aString, aString, aString]);
  FHTMLWriter := HTMLWriterFactory('this');
  FHTMLWriter.AddText(aString);
  Result := FHTMLWriter.CloseTag.AsHTML;
  CheckEquals(ExpectedValue, Result);

  // try adding text with brackets in it
  aString := '<groob>';
  ExpectedValue := HTML(aString);
  FHTMLWriter := HTMLWriterFactory('html');
  FHTMLWriter.AddText(aString);
  Result := FHTMLWriter.CloseTag.AsHTML;
  CheckEquals(ExpectedValue, Result);

end;

procedure TestTHTMLWriter.TestAddHardRule;
var
  TestResult: string;
  ExpectedResult: string;
begin
  ExpectedResult := HTML('<hr />');
  TestResult := HTMLWriterFactory(cHTML).AddHardRule.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<hr>');
  TestResult := HTMLWriterFactory(cHTML).AddHardRule('', ucsDoNotUseCloseSlash).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<hr clear="left" />');
  TestResult := HTMLWriterFactory(cHTML).AddHardRule('clear="left"', ucsUseCloseSlash).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddHead;
var
  ExpectedValue: string;
  TestResult: string;
begin
  FHTMLWriter := HTMLWriterFactory('html');
  ExpectedValue := HTML('<head></head>');
  // Multiple close tags should be fine
  TestResult := FHTMLWriter.OpenHead.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedValue, TestResult);
end;

procedure TestTHTMLWriter.TestOpenBody;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenBody.AsHTML;
  ExpectedResult := '<html><body';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBody.CloseTag.AsHTML;
  ExpectedResult := '<html><body></body>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBody.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><body></body></html>';
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenParagraph;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenParagraph.AsHTML;
  ExpectedResult := '<html><p';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenParagraph.CloseTag.AsHTML;
  ExpectedResult := '<html><p></p>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenParagraph.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><p></p></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenParagraph.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><p>blah</p></html>';
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenParagraphWithID;
var
  TestResult: string;
  ExpectedResult: string;
  TempStyle: string;
begin
  TempStyle := 'nerster: hormle';
  ExpectedResult := HTML(Format('<p id="%s"></p>', [TempStyle]));
  TestResult := HTMLWriterFactory('html').OpenParagraphWithID(TempStyle).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenParagraphWithStyle;
var
  TestResult: string;
  ExpectedResult: string;
  TempStyle: string;
begin
  TempStyle := 'nerster: hormle';
  ExpectedResult := HTML(Format('<p style="%s"></p>', [TempStyle]));
  TestResult := HTMLWriterFactory('html').OpenParagraphWithStyle(TempStyle).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddParagraphTextWithStyle;
var
  TestResult: string;
  ExpectedResult: string;
  TempStyle: string;
  TempText: string;
begin
  TempStyle := 'nerster: hormle';
  TempText := 'jimkast';
  ExpectedResult := HTML(Format('<p style="%s">%s</p>', [TempStyle, TempText]));
  TestResult := HTMLWriterFactory('html').AddParagraphTextWithStyle(TempText, TempStyle).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddParagraphTextWithID;
var
  TestResult: string;
  ExpectedResult: string;
  TempStyle: string;
  TempText: string;
begin
  TempStyle := 'nerster: hormle';
  TempText := 'jimkast';
  ExpectedResult := HTML(Format('<p id="%s">%s</p>', [TempStyle, TempText]));
  TestResult := HTMLWriterFactory('html').AddParagraphTextwithID(TempText, TempStyle).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenSample;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftSample];

  TestResult := HTMLWriterFactory('html').OpenSample.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenSample.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenSample.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenSample.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenScript;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenScript.AsHTML;
  ExpectedResult := '<html><script';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenScript.CloseTag.AsHTML;
  ExpectedResult := '<html><script></script>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenScript.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><script></script></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenScript.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><script>blah</script></html>';
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenSmall;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftSmall];

  TestResult := HTMLWriterFactory('html').OpenSmall.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenSmall.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenSmall.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenSmall.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenSpan;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenSpan.AsHTML;
  ExpectedResult := '<html><span';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenSpan.CloseTag.AsHTML;
  ExpectedResult := '<html><span></span>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenSpan.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><span></span></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenSpan.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><span>blah</span></html>';
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenDefinition;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftDefinition];

  TestResult := HTMLWriterFactory('html').OpenDefinition.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenDefinition.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenDefinition.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenDefinition.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenDelete;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftDelete];

  TestResult := HTMLWriterFactory('html').OpenDelete.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenDelete.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenDelete.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenDelete.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenDiv;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenDiv.AsHTML;
  ExpectedResult := '<html><div';

  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenDiv.CloseTag.AsHTML;
  ExpectedResult := '<html><div></div>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenDiv.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><div></div></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenDiv.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><div>blah</div></html>';
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenAbbreviation;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftAbbreviation];

  TestResult := HTMLWriterFactory('html').OpenAbbreviation.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenAbbreviation.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenAbbreviation.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenAbbreviation.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenAcronym;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftAcronym];

  TestResult := HTMLWriterFactory('html').OpenAcronym.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenAcronym.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenAcronym.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenAcronym.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenAddress;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftAddress];

  TestResult := HTMLWriterFactory('html').OpenAddress.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenAddress.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenAddress.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenAddress.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenAnchor;
var
  TestResult: string;
  ExpectedResult: string;
  TempText: string;
  TempHREF: string;
begin
  TestResult := HTMLWriterFactory('html').OpenAnchor.AsHTML;
  ExpectedResult := '<html><a';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenAnchor.CloseTag.AsHTML;
  ExpectedResult := '<html><a></a>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenAnchor.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><a></a></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenAnchor.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><a>blah</a></html>';
  CheckEquals(ExpectedResult, TestResult);

  TempHREF := 'http://www.nickhodges.com';
  TempText := 'Nick Hodges';
  TestResult := HTMLWriterFactory('html').OpenAnchor(TempHREF, TempText).CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><a href="%s">%s</a></html>', [TempHREF, TempText]);
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenBDO;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftBDO];

  TestResult := HTMLWriterFactory('html').OpenBDO.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBDO.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBDO.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBDO.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenBig;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftBig];

  TestResult := HTMLWriterFactory('html').OpenBig.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBig.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBig.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBig.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenBlockQuote;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenBlockQuote.AsHTML;
  ExpectedResult := '<html><blockquote';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBlockQuote.CloseTag.AsHTML;
  ExpectedResult := '<html><blockquote></blockquote>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBlockQuote.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><blockquote></blockquote></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBlockQuote.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><blockquote>blah</blockquote></html>';
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddParagraphText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
begin
  TempString := 'grundle';

  ExpectedResult := '<html><p>' + TempString + '</p>';
  TestResult := HTMLWriterFactory('html').AddParagraphText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<p>' + TempString + '</p>');
  TestResult := HTMLWriterFactory('html').AddParagraphText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddSampleText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftSample];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddSampleText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddSampleText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddScript;
var
  TestResult, ExpectedResult: string;
  TempString: string;
begin
  TempString := 'grundle';

  ExpectedResult := '<html><script>' + TempString + '</script>';
  TestResult := HTMLWriterFactory('html').AddScript(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<script>' + TempString + '</script>');
  TestResult := HTMLWriterFactory('html').AddScript(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddSmallText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftSmall];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddSmallText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddSmallText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddSpanText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
begin
  TempString := 'grundle';

  ExpectedResult := '<html><span>' + TempString + '</span>';
  TestResult := HTMLWriterFactory('html').AddSpanText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<span>' + TempString + '</span>');
  TestResult := HTMLWriterFactory('html').AddSpanText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddDefinitionText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftDefinition];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddDefinitionText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddDefinitionText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddDeleteText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftDelete];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddDeleteText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddDeleteText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddDivText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
begin
  TempString := 'grundle';

  ExpectedResult := '<html><div>' + TempString + '</div>';
  TestResult := HTMLWriterFactory('html').AddDivText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<div>' + TempString + '</div>');
  TestResult := HTMLWriterFactory('html').AddDivText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddDivTextWithID;
var
  TempID: string;
  TempString: string;
  TestResult: string;
  ExpectedResult: string;
begin
  TempString := 'flooble';
  TempID := 'main';
  ExpectedResult := HTML(Format('<div id="%s">%s</div>', [TempID, TempString]));
  TestResult := HTMLWriterFactory(cHTML).AddDivTextWithID(TempString, TempID).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddDivTextWithStyle;
var
  TempStyle: string;
  TempString: string;
  TestResult: string;
  ExpectedResult: string;
begin
  TempString := 'flooble';
  TempStyle := 'border-top:1px solid #c9d7f1;font-size:1px';
  ExpectedResult := HTML(Format('<div style="%s">%s</div>', [TempStyle, TempString]));
  TestResult := HTMLWriterFactory(cHTML).AddDivTextWithStyle(TempString, TempStyle).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenBold;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenBold.AsHTML;
  ExpectedResult := '<html><b';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBold.CloseTag.AsHTML;
  ExpectedResult := '<html><b></b>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBold.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><b></b></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenBold.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><b>blah</b></html>';
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenEmphasis;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenEmphasis.AsHTML;
  ExpectedResult := '<html><em';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenEmphasis.CloseTag.AsHTML;
  ExpectedResult := '<html><em></em>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenEmphasis.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><em></em></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenEmphasis.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><em>blah</em></html>';
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestFieldSetAndLegend;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := cFieldSet;

  TestResult := HTMLWriterFactory('html').OpenFieldSet.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenFieldSet.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenFieldSet.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenFieldSet.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenFieldSet.OpenLegend.AsHTML;
  ExpectedResult := Format('<html><%s><%s', [cFieldSet, cLegend]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenFieldSet.OpenLegend.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s><%s></%s>', [cFieldSet, cLegend, cLegend]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenFieldSet.OpenLegend.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s><%s></%s></%s>', [cFieldSet, cLegend, cLegend, cFieldSet]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenFieldSet.AddLegend('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s><%s>blah</%s></%s></html>', [cFieldSet, cLegend, cLegend, cFieldSet]);
  CheckEquals(ExpectedResult, TestResult);

  try
    TestResult := HTMLWriterFactory(cHTML).OpenBody.OpenLegend.CloseTag.CloseTag.CloseTag.AsHTML;
    Check(False, 'Failed to raise an exception adding a <legend> tag outside the <fieldset> tag. ');
  except
    on E: ENotInFieldsetTagException do
    begin
      Check(True, 'Successfully raised the ENotInFieldsetTagException.  All is well.');
    end;
  end;

end;

procedure TestTHTMLWriter.TestOpenFont;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
  TempColor: string;
begin
  TempTag := TFormatTypeStrings[ftFont];

  TestResult := HTMLWriterFactory('html').OpenFont.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenFont.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenFont.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenFont.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TempColor := 'red';
  TestResult := HTMLWriterFactory('html').OpenFont.AddAttribute('color', TempColor).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s color="%s">blah</%s></html>', [TempTag, TempColor, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenStrike;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftStrike];

  TestResult := HTMLWriterFactory('html').OpenStrike.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenStrike.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenStrike.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenStrike.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenStrong;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenStrong.AsHTML;
  ExpectedResult := '<html><strong';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenStrong.CloseTag.AsHTML;
  ExpectedResult := '<html><strong></strong>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenStrong.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><strong></strong></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenStrong.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><strong>blah</strong></html>';
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenTable;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenTable.AsHTML;
  ExpectedResult := '<html><table';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable.CloseTag.AsHTML;
  ExpectedResult := '<html><table></table>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table></table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table>blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(3).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table border="3">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(3, 4).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table border="3" cellpadding="4">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(3, 4, 5).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table border="3" cellpadding="4" cellspacing="5">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(-1, 4, 5).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table cellpadding="4" cellspacing="5">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(-1, -1, 5).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table cellspacing="5">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(3, -1, 5).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table border="3" cellspacing="5">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(-1, -1, 5).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table cellspacing="5">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  // Width
  TestResult := HTMLWriterFactory('html').OpenTable(3, 4, 5, THTMLWidth.Create(6, False)).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table border="3" cellpadding="4" cellspacing="5" width="6">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(-1, 4, 5, THTMLWidth.Create(6, False)).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table cellpadding="4" cellspacing="5" width="6">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(-1, -1, 5, THTMLWidth.Create(6, False)).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table cellspacing="5" width="6">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(3, -1, 5, THTMLWidth.Create(6, False)).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table border="3" cellspacing="5" width="6">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(-1, -1, 5, THTMLWidth.Create(6, False)).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table cellspacing="5" width="6">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  // Width as percentage
  TestResult := HTMLWriterFactory('html').OpenTable(3, 4, 5, THTMLWidth.Create(6, True)).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table border="3" cellpadding="4" cellspacing="5" width="6%">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(-1, 4, 5, THTMLWidth.Create(6, True)).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table cellpadding="4" cellspacing="5" width="6%">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(-1, -1, 5, THTMLWidth.Create(6, True)).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table cellspacing="5" width="6%">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(3, -1, 5, THTMLWidth.Create(6, True)).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table border="3" cellspacing="5" width="6%">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable(-1, -1, 5, THTMLWidth.Create(6, True)).AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table cellspacing="5" width="6%">blah</table></html>';
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenTableData;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenTable.OpenTableRow.OpenTableData.AsHTML;
  ExpectedResult := '<html><table><tr><td';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable.OpenTableRow.OpenTableData.CloseTag.AsHTML;
  ExpectedResult := '<html><table><tr><td></td>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable.OpenTableRow.OpenTableData.CloseTag.CloseTag.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table><tr><td></td></tr></table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable.OpenTableRow.OpenTableData.AddText('blah').CloseTag.CloseTag.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table><tr><td>blah</td></tr></table></html>';
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddTableData;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenTable.OpenTableRow.AddTableData('blah').CloseTag.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table><tr><td>blah</td></tr></table></html>';
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenTableRow;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenTable.OpenTableRow.AsHTML;
  ExpectedResult := '<html><table><tr';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable.OpenTableRow.CloseTag.AsHTML;
  ExpectedResult := '<html><table><tr></tr>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable.OpenTableRow.CloseTag.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table><tr></tr></table></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTable.OpenTableRow.AddText('blah').CloseTag.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><table><tr>blah</tr></table></html>';
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenTeletype;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftTeletype];

  TestResult := HTMLWriterFactory('html').OpenTeletype.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTeletype.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTeletype.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenTeletype.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenTitle;
var
  TestResult: string;
  ExpectedResult: string;
begin
  ExpectedResult := '<html><head><title';
  TestResult := HTMLWriterFactory(cHTML).OpenHead.OpenTitle.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><head><title></title>';
  TestResult := HTMLWriterFactory(cHTML).OpenHead.OpenTitle.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><head><title></title></head>';
  TestResult := HTMLWriterFactory(cHTML).OpenHead.OpenTitle.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><head><title></title></head></html>';
  TestResult := HTMLWriterFactory(cHTML).OpenHead.OpenTitle.CloseTag.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><head><title>hethland</title></head></html>';
  TestResult := HTMLWriterFactory(cHTML).OpenHead.OpenTitle.AddText('hethland').CloseTag.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddTitle;
var
  TestResult: string;
  ExpectedResult: string;
begin
  ExpectedResult := '<html><head><title>hethland</title></head></html>';
  TestResult := HTMLWriterFactory(cHTML).OpenHead.AddTitle('hethland').CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  try
    TestResult := HTMLWriterFactory(cHTML).AddTitle('threek').CloseTag.AsHTML;
    Check(False, 'Failed to raise a EHeadTagRequiredHTMLException when adding a title outside of a <head> tag');
  except
    on E: EHeadTagRequiredHTMLException do
    begin
      Check(True, 'All is well -- the EHeadTagRequiredHTMLException was properly raised. ');
    end;
  end;

end;

procedure TestTHTMLWriter.TestOpenPre;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenPre.AsHTML;
  ExpectedResult := '<html><pre';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenPre.CloseTag.AsHTML;
  ExpectedResult := '<html><pre></pre>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenPre.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><pre></pre></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenPre.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><pre>blah</pre></html>';
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenCenter;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftCenter];

  TestResult := HTMLWriterFactory('html').OpenCenter.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenCenter.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenCenter.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenCenter.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenQuotation;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftQuotation];

  TestResult := HTMLWriterFactory('html').OpenQuotation.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenQuotation.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenQuotation.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenQuotation.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenCite;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenCite.AsHTML;
  ExpectedResult := '<html><cite';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenCite.CloseTag.AsHTML;
  ExpectedResult := '<html><cite></cite>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenCite.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><cite></cite></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenCite.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><cite>blah</cite></html>';
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenCode;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftCode];

  TestResult := HTMLWriterFactory('html').OpenCode.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenCode.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenCode.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenCode.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenComment;
var
  TestResult: string;
  TempString: string;
  ExpectedResult: string;
begin
  TempString := 'wertybin';
  ExpectedResult := HTML(Format('<!-- %s -->', [TempString]));
  TestResult := HTMLWriterFactory(cHTML).OpenComment.AddText(TempString).CloseComment.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestCloseComment;
var
  TestResult: string;
  TempString: string;
  ExpectedResult: string;
begin
  TempString := 'gloppet';
  ExpectedResult := HTML(Format('<span><!-- %s --></span>', [TempString]));
  TestResult := HTMLWriterFactory(cHTML).OpenSpan.OpenComment.AddText(TempString).CloseComment.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  try
    TestResult := HTMLWriterFactory(cHTML).OpenBody.CloseComment.CloseTag.AsHTML;
    Check(False, 'Failed to raise an exception when closing a comment outside of a comment tag. ');
  except
    on E: ENotInCommentTagException do
    begin
      Check(True, 'Successfully raised the ENotInCommentTagException.  All is well.');
    end;
  end;

end;

procedure TestTHTMLWriter.TestAddCodeText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftCode];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddCodeText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddCodeText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddComment;
var
  TestResult: string;
  TempString: string;
  ExpectedResult: string;
begin
  TempString := 'gropter';
  ExpectedResult := HTML(Format('<!-- %s -->', [TempString]));
  TestResult := HTMLWriterFactory(cHTML).AddComment(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenIFrame;
var
  TestResult: string;
  ExpectedResult: string;
  Temp: string;
begin
  ExpectedResult := HTML('<iframe></iframe>');
  TestResult := HTMLWriterFactory(cHTML).OpenIFrame.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  Temp := 'http://www.nickhodges.com';
  ExpectedResult := Format(HTML('<iframe src="%s"></iframe>'), [Temp]);
  TestResult := HTMLWriterFactory(cHTML).OpenIFrame(Temp).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := Format(HTML('<iframe src="%s" width="42" height="300"></iframe>'), [Temp]);
  TestResult := HTMLWriterFactory(cHTML).OpenIFrame(Temp, THTMLWidth.Create(42, False), 300).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenImage;
var
  TestResult: string;
  ExpectedResult: string;
  TempSource: string;
begin
  TestResult := HTMLWriterFactory('html').OpenImage.AsHTML;
  ExpectedResult := '<html><img';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenImage.CloseTag.AsHTML;
  ExpectedResult := '<html><img />';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenImage.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><img /></html>';
  CheckEquals(ExpectedResult, TestResult);

  TempSource := 'blah.jpg';
  TestResult := HTMLWriterFactory(cHTML).OpenImage(TempSource).CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><img src="%s" /></html>', [TempSource]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddImage;
var
  TestResult: string;
  ExpectedResult: string;
  TempSource: string;
begin
  TempSource := 'blah.jpg';
  TestResult := HTMLWriterFactory(cHTML).AddImage(TempSource).CloseTag.AsHTML;
  ExpectedResult := Format('<html><img src="%s" /></html>', [TempSource]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenItalic;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenItalic.AsHTML;
  ExpectedResult := '<html><i';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenItalic.CloseTag.AsHTML;
  ExpectedResult := '<html><i></i>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenItalic.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><i></i></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenItalic.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><i>blah</i></html>';
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenKeyboard;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftKeyboard];

  TestResult := HTMLWriterFactory('html').OpenKeyboard.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenKeyboard.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenKeyboard.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenKeyboard.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenMeta;
var
  TestResult: string;
  ExpectedResult: string;
begin
  ExpectedResult := '<html><head><meta /></head></html>';
  TestResult := HTMLWriterFactory(cHTML).OpenHead.OpenMeta.CloseTag.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  { DONE -oNick : Need to test that an exception gets raised if OpenMeta is called outside a <head> tag. }

  try
    TestResult := HTMLWriterFactory(cHTML).OpenBody.OpenMeta.CloseTag.CloseTag.AsHTML;
    Check(False, 'Failed to raise an exception adding a <meta> tag outside the <head> tag. ');
  except
    on E: EHeadTagRequiredHTMLException do
    begin
      Check(True, 'Successfully raised the EMetaOnlyInHeadTagHTMLException.  All is well.');
    end;
  end;

end;

procedure TestTHTMLWriter.TestOpenOrderedList;
var
  TestResult, ExpectedResult: string;
begin

  ExpectedResult := '<html><ol></ol></html>';
  TestResult := HTMLWriterFactory('html').OpenOrderedList().CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><ol type="1"></ol></html>';
  TestResult := HTMLWriterFactory('html').OpenOrderedList(ntNumber).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><ol type="A"></ol></html>';
  TestResult := HTMLWriterFactory('html').OpenOrderedList(ntUpperCase).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><ol type="i"></ol></html>';
  TestResult := HTMLWriterFactory('html').OpenOrderedList(ntLowerRoman).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenUnderline;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenUnderline.AsHTML;
  ExpectedResult := '<html><u';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenUnderline.CloseTag.AsHTML;
  ExpectedResult := '<html><u></u>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenUnderline.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><u></u></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenUnderline.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><u>blah</u></html>';
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenUnorderedList;
var
  TestResult, ExpectedResult: string;
begin

  ExpectedResult := '<html><ul></ul></html>';
  TestResult := HTMLWriterFactory('html').OpenUnorderedList().CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><ul type="disc"></ul></html>';
  TestResult := HTMLWriterFactory('html').OpenUnorderedList(bsDisc).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><ul type="circle"></ul></html>';
  TestResult := HTMLWriterFactory('html').OpenUnorderedList(bsCircle).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><ul type="square"></ul></html>';
  TestResult := HTMLWriterFactory('html').OpenUnorderedList(bsSquare).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenVariable;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := TFormatTypeStrings[ftVariable];

  TestResult := HTMLWriterFactory('html').OpenVariable.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenVariable.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenVariable.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenVariable.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenForm;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := cForm;

  TestResult := HTMLWriterFactory('html').OpenForm.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenForm.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenForm.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenForm.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestThatExceptionsAreRaised;
var
  TestResult: string;
begin
  try
    TestResult := HTMLWriterFactory(cHTML).AddMetaNamedContent('This', 'That').CloseTag.AsHTML;
    Check(False, 'Failed to raise EHeadTagRequiredHTMLException when adding <meta> tag outside <head> tag');
  except
    on E: EHeadTagRequiredHTMLException do
    begin
      Check(True, 'Successfully raised EHeadTagRequiredHTMLException when it was supposed to be raised.');
    end;
  end;

  try
    TestResult := HTMLWriterFactory(cHTML).OpenListItem.CloseTag.AsHTML;
    Check(False, 'Failed to raise ENotInListTagException when calling OpenList Item outside of a lise');
  except
    on E: ENotInListTagException do
    begin
      Check(True, 'Properly called ENotInListTagException when outside of a list.  All is well.');
    end;
  end;

  try
    TestResult := HTMLWriterFactory(cHTML).AddTableData('gremter').CloseTag.AsHTML;
    Check(False, 'Failed to raise ENotInTableTagException when trying to add a Table Row outside of a table');
  except
    on E: ENotInTableTagException do
    begin
      Check(True, 'Properly called ENotInTableTagException when adding a TableRow outside of a table.');
    end;
  end;
end;

procedure TestTHTMLWriter.TestTHTMLWidth1;
var
  TempWidth: THTMLWidth;
  ExpectedResult: string;
  TestResult: string;
begin
  TempWidth.IsPercentage := False;
  TempWidth.Width := 42;
  ExpectedResult := '';
  TestResult := TempWidth.AsPercentage;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestTHTMLWidth2;
var
  TempWidth: THTMLWidth;
  ExpectedResult: string;
  TestResult: string;
begin
  TempWidth.Width := 42;
  TempWidth.IsPercentage := True;
  ExpectedResult := '42%';
  TestResult := TempWidth.AsPercentage;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestOpenListItem;
var
  TestResult, ExpectedResult: string;
  Temp: string;
begin
  Temp := 'bloople';

  ExpectedResult := '<html><ul><li></li></ul></html>';
  TestResult := HTMLWriterFactory('html').OpenUnorderedList().OpenListItem.CloseTag.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><ul type="disc"><li></li></ul></html>';
  TestResult := HTMLWriterFactory('html').OpenUnorderedList(bsDisc).OpenListItem.CloseTag.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><ul type="circle"><li></li></ul></html>';
  TestResult := HTMLWriterFactory('html').OpenUnorderedList(bsCircle).OpenListItem.CloseTag.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := '<html><ul type="square"><li></li></ul></html>';
  TestResult := HTMLWriterFactory('html').OpenUnorderedList(bsSquare).OpenListItem.CloseTag.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := Format('<html><ul type="square"><li>%s</li></ul></html>', [Temp]);
  TestResult := HTMLWriterFactory('html').OpenUnorderedList(bsSquare).OpenListItem.AddText(Temp).CloseTag.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := Format('<html><ul type="square"><li type="zoob">%s</li></ul></html>', [Temp]);
  TestResult := HTMLWriterFactory('html').OpenUnorderedList(bsSquare).OpenListItem.AddAttribute('type', 'zoob').AddText(Temp).CloseTag.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  try
    TestResult := HTMLWriterFactory(cHTML).OpenBody.OpenDiv.OpenListItem.CloseList.CloseTag.CloseTag.CloseTag.AsHTML;
    Check(False, 'Failed to see that a list item was being added outside a list');
  except
    on E: ENotInListTagException do
      Check(True, 'Successfully raised the ENotInListTagException.  All is well.');
  end;

end;

procedure TestTHTMLWriter.TestAddListItem;
var
  TestResult, ExpectedResult: string;
  Temp: string;
begin
  Temp := 'bloople';

  ExpectedResult := Format('<html><ul type="square"><li>%s</li></ul></html>', [Temp]);
  TestResult := HTMLWriterFactory('html').OpenUnorderedList(bsSquare).AddListItem(Temp).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

function TestTHTMLWriter.HTML(aString: string): string;
begin
  Result := Format('<html>%s</html>', [aString]);
end;

function TestTHTMLWriter.HTMLWriterFactory(aTagName: string): THTMLWriter;
begin
  if FHTMLWriter <> nil then
  begin
    FHTMLWriter.Free;
    FHTMLWriter := nil;
  end;
  Result := THTMLWriter.Create(aTagName);
end;

procedure TestTHTMLWriter.TestAddBlockQuoteText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
begin
  TempString := 'grundle';

  ExpectedResult := '<html><blockquote>' + TempString + '</blockquote>';
  TestResult := HTMLWriterFactory('html').AddBlockQuoteText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<blockquote>' + TempString + '</blockquote>');
  TestResult := HTMLWriterFactory('html').AddBlockQuoteText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddBoldText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
begin
  TempString := 'grundle';

  ExpectedResult := '<html><b>' + TempString + '</b>';
  TestResult := HTMLWriterFactory('html').AddBoldText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<b>' + TempString + '</b>');
  TestResult := HTMLWriterFactory('html').AddBoldText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddItalicText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
begin
  TempString := 'grundle';

  ExpectedResult := '<html><i>' + TempString + '</i>';
  TestResult := HTMLWriterFactory('html').AddItalicText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<i>' + TempString + '</i>');
  TestResult := HTMLWriterFactory('html').AddItalicText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddKeyboardText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftKeyboard];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddKeyboardText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddKeyboardText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddLineBreak;
var
  TestResult: string;
  ExpectedResult: string;
begin
  ExpectedResult := HTML('<br />');
  TestResult := HTMLWriterFactory(cHTML).AddLineBreak().CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<br>');
  TestResult := HTMLWriterFactory(cHTML).AddLineBreak(cvNoValue, ucsDoNotUseCloseSlash).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<br clear="left">');
  TestResult := HTMLWriterFactory(cHTML).AddLineBreak(cvLeft, ucsDoNotUseCloseSlash).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<br clear="left" />');
  TestResult := HTMLWriterFactory(cHTML).AddLineBreak(cvLeft, ucsUseCloseSlash).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddAnchor;
var
  TestResult: string;
  ExpectedResult: string;
const
  TempHREF = 'http://www.nickhodges.com';
  TempText = 'Nick Hodges';
begin
  ExpectedResult := Format(HTML('<a href="%s">%s</a>'), [TempHREF, TempText]);
  TestResult := HTMLWriterFactory(cHTML).AddAnchor(TempHREF, TempText).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddMetaNamedContent;
var
  TestResult, ExpectedResult: string;
  TempName: string;
  TempContent: string;
  Temp: THTMLWriter;
begin
  TempName := 'Snerdo';
  TempContent := 'derfle';
  ExpectedResult := '<html><head><meta name="%s" content="%s" /></head></html>';
  ExpectedResult := Format(ExpectedResult, [TempName, TempContent]);
  Temp := HTMLWriterFactory(cHTML);
  Temp := Temp.OpenHead;
  Temp := Temp.OpenMeta;
  Temp := Temp.AddMetaNamedContent(TempName, TempContent);
  Temp := Temp.CloseTag;
  Temp := Temp.CloseTag;
  Temp := Temp.CloseTag;
  TestResult := Temp.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddUnderlinedText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
begin
  TempString := 'grundle';

  ExpectedResult := '<html><u>' + TempString + '</u>';
  TestResult := HTMLWriterFactory('html').AddUnderlinedText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML('<u>' + TempString + '</u>');
  TestResult := HTMLWriterFactory('html').AddUnderlinedText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddVariableText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftVariable];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddVariableText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddVariableText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddEmphasisText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := 'em';

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddEmphasisText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddEmphasisText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddFontText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := 'font';

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddFontText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddFontText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddStrikeText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftStrike];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddStrikeText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddStrikeText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddStrongText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := 'strong';

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddStrongText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddStrongText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddAcronymText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftAcronym];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddAcronymText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddAcronymText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddAddressText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftAddress];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddAddressText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddAddressText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddBase;
var
  TestResult, ExpectedResult: string;
  Temp: string;
  TempTarget: TTargetType;
  TempWriter: THTMLWriter;
const
  TempURL = 'http://www.nickhodges.com';
begin
  ExpectedResult := Format(HTML('<head><base /></head>'), [TempURL]);
  TempWriter := HTMLWriterFactory(cHTML).OpenHead.OpenBase;
  TestResult := TempWriter.CloseTag.CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := Format(HTML('<head><base href="%s" /></head>'), [TempURL]);
  TestResult := HTMLWriterFactory(cHTML).OpenHead.AddBase(TempURL).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := Format(HTML('<head><base target="%s" /></head>'), [TTargetTypeStrings[ttBlank]]);
  TestResult := HTMLWriterFactory(cHTML).OpenHead.AddBase(ttBlank).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  for TempTarget := ttBlank to ttTop do
  begin
    ExpectedResult := Format(HTML('<head><base target="%s" /></head>'), [TTargetTypeStrings[TempTarget]]);
    TestResult := HTMLWriterFactory(cHTML).OpenHead.AddBase(TempTarget).CloseTag.CloseTag.AsHTML;
    CheckEquals(ExpectedResult, TestResult);
  end;

  Temp := 'flater';
  ExpectedResult := Format(HTML('<head><base target="%s" /></head>'), [Temp]);
  TestResult := HTMLWriterFactory(cHTML).OpenHead.AddBase(ttFrameName, Temp).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddBDOText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftBDO];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddBDOText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddBDOText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddBigText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftBig];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddBigText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddBigText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddAbbreviationText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftAbbreviation];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddAbbreviationText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddAbbreviationText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddPreformattedText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftPreformatted];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddPreformattedText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddPreformattedText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddQuotationText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := TFormatTypeStrings[ftQuotation];

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddQuotationText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddQuotationText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddCenterText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := 'center';

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddCenterText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddCenterText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddCitationText;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := 'cite';

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddCitationText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddCitationText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenHeading1;
var
  TestResult: string;
  ExpectedResult: string;
begin
  TestResult := HTMLWriterFactory('html').OpenHeading1.AsHTML;
  ExpectedResult := '<html><h1';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading1.CloseTag.AsHTML;
  ExpectedResult := '<html><h1></h1>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading1.CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><h1></h1></html>';
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading1.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := '<html><h1>blah</h1></html>';
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenHeading2;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := 'h2';
  TestResult := HTMLWriterFactory('html').OpenHeading2.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading2.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]); ;
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading2.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading2.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenHeading3;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := 'h3';
  TestResult := HTMLWriterFactory('html').OpenHeading3.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading3.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]); ;
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading3.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading3.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenHeading4;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := 'h4';
  TestResult := HTMLWriterFactory('html').OpenHeading4.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading4.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]); ;
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading4.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading4.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenHeading5;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := 'h5';
  TestResult := HTMLWriterFactory('html').OpenHeading5.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading5.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]); ;
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading5.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading5.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestOpenHeading6;
var
  TestResult: string;
  ExpectedResult: string;
  TempTag: string;
begin
  TempTag := 'h6';
  TestResult := HTMLWriterFactory('html').OpenHeading6.AsHTML;
  ExpectedResult := Format('<html><%s', [TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading6.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s>', [TempTag, TempTag]); ;
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading6.CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s></%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);

  TestResult := HTMLWriterFactory('html').OpenHeading6.AddText('blah').CloseTag.CloseTag.AsHTML;
  ExpectedResult := Format('<html><%s>blah</%s></html>', [TempTag, TempTag]);
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddHeading1Text;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := 'h1';

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddHeading1Text(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddHeading1Text(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddHeading2Text;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := 'h2';

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddHeading2Text(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddHeading2Text(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddHeading3Text;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := 'h3';

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddHeading3Text(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddHeading3Text(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddHeading4Text;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := 'h4';

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddHeading4Text(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddHeading4Text(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddHeading5Text;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := 'h5';

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddHeading5Text(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddHeading5Text(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddHeading6Text;
var
  TestResult, ExpectedResult: string;
  TempString: string;
  TempTag: string;
begin
  TempString := 'grundle';
  TempTag := 'h6';

  ExpectedResult := Format('<html><%s>%s</%s>', [TempTag, TempString, TempTag]);
  TestResult := HTMLWriterFactory('html').AddHeading6Text(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<%s>%s</%s>', [TempTag, TempString, TempTag]));
  TestResult := HTMLWriterFactory('html').AddHeading6Text(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddStyle;
var
  TestResult, ExpectedResult: string;
  TempStyle: string;
  TempString: string;
begin
  TempStyle := 'font-size: small';
  TempString := 'blooker';
  ExpectedResult := Format('<span style="%s"', [TempStyle]);
  TestResult := HTMLWriterFactory('span').AddStyle(TempStyle).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := ExpectedResult + '>' + TempString;
  TestResult := HTMLWriterFactory('span').AddStyle(TempStyle).AddText(TempString).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := ExpectedResult + '</span>';
  TestResult := HTMLWriterFactory('span').AddStyle(TempStyle).AddText(TempString).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddClass;
var
  TestResult, ExpectedResult: string;
  TempClassName: string;
begin
  TempClassName := 'harbie';

  ExpectedResult := Format('<html><span class="%s"', [TempClassName]);
  TestResult := HTMLWriterFactory('html').OpenSpan.AddClass(TempClassName).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<span class="%s"></span>', [TempClassName]));
  TestResult := HTMLWriterFactory('html').OpenSpan.AddClass(TempClassName).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddID;
var
  TestResult, ExpectedResult: string;
  TempClassName: string;
begin
  TempClassName := 'harbie';

  ExpectedResult := Format('<html><span id="%s"', [TempClassName]);
  TestResult := HTMLWriterFactory('html').OpenSpan.AddID(TempClassName).AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := HTML(Format('<span id="%s"></span>', [TempClassName]));
  TestResult := HTMLWriterFactory('html').OpenSpan.AddID(TempClassName).CloseTag.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddIFrame;
var
  ExpectedResult: string;
  TestResult: string;
  Temp: string;
  TempAlt: string;
begin
  Temp := 'http://www.nickhodges.com';
  TempAlt := 'Hepger';
  ExpectedResult := Format(HTML('<iframe src="%s" width="42" height="300">%s</iframe>'), [Temp, TempAlt]);
  TestResult := HTMLWriterFactory(cHTML).AddIFrame(Temp, TempAlt, THTMLWidth.Create(42, False), 300).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddAttribute;
var
  TestResult: string;
  TempTagName: string;
  TempAttributeName, TempAttributeValue: string;
  ExpectedResult: string;
begin
  TempTagName := 'treaster';
  TempAttributeName := 'thresa';
  TempAttributeValue := 'grenar';

  ExpectedResult := Format('<%s %s></%s>', [TempTagName, TempAttributeName, TempTagName]);
  TestResult := HTMLWriterFactory(TempTagName).AddAttribute(TempAttributeName).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := Format('<%s %s="%s"></%s>', [TempTagName, TempAttributeName, TempAttributeValue, TempTagName]);
  TestResult := HTMLWriterFactory(TempTagName).AddAttribute(TempAttributeName, TempAttributeValue).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestCloseTag;
var
  TestResult: string;
  TempTagName: string;
  ExpectedResult: string;
begin
  TempTagName := 'gretis';
  ExpectedResult := Format('<%s></%s>', [TempTagName, TempTagName]);
  TestResult := HTMLWriterFactory(TempTagName).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  // try
  // TestResult := HTMLWriterFactory(cHTML).OpenHead.CloseTag.CloseTag.CloseTag.CloseTag.CloseTag.AsHTML;
  // Check(False, 'Failed to rais an exception when an extra Closetag was called.');
  // except
  // on E: ETryingToCloseClosedTag do
  // begin
  // Check(True, 'Successfully raised the ETryingToCloseClosedTag.  All is well.');
  // end;
  // end;

  { DONE : Make sure that an extra close tag raises an exception }

end;

procedure TestTHTMLWriter.TestConstructorException;
var
  TestValue: string;
begin

  try
    TestValue := HTMLWriterFactory('').CloseTag.AsHTML;
    Check(False, 'Failed to raise EHTMLWriterEmptyTagException when passing an empty tag to constructor');
  except
    on E: EHTMLWriterEmptyTagException do
    begin
      Check(True, 'All is well -- succsessfully raised the EHTMLWriterEmptyTagException in constructor');
    end;
  end;
end;

procedure TestTHTMLWriter.TestCreateDocument;
var
  TestResult: string;
  ExpectedResult: string;
begin
  ExpectedResult := '<html></html>';
  TestResult := THTMLWriter.CreateDocument.CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  ExpectedResult := THTMLDocTypeStrings[dtHTML401Strict] + '<html></html>';
  TestResult := THTMLWriter.CreateDocument(dtHTML401Strict).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestLoadSave;
var
  InString, OutString: string;
  Temp: THTMLWriter;
const
  cFilename = 'test.html';
begin
  try
    Temp := HTMLWriterFactory(cHTML).OpenHead.AddTitle('This is the title').CloseTag.OpenBody.AddBoldText('This is bold').CloseTag.CloseTag;
    InString := Temp.AsHTML;
    Temp.SaveToFile(cFilename);
    Temp.LoadFromFile(cFilename);
    OutString := Temp.AsHTML;
    CheckEquals(OutString, InString);
  finally
    SysUtils.DeleteFile(cFilename);
  end;
end;

procedure TestTHTMLWriter.TestNonHTMLTag;
var
  TestResult: string;
  ExpectedResult: string;
  TempStr: string;
begin
  ExpectedResult := '<b></b>';
  TestResult := THTMLWriter.Create(TFormatTypeStrings[ftBold]).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

  TempStr := 'mashtes';
  ExpectedResult := Format('<b>%s</b>', [TempStr]);
  TestResult := THTMLWriter.Create(TFormatTypeStrings[ftBold]).AddText(TempStr).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);

end;

procedure TestTHTMLWriter.TestAddSpanTextWithStyle;
var
  TempStyle: string;
  TempString: string;
  TestResult: string;
  ExpectedResult: string;
begin
  TempString := 'flooble';
  TempStyle := 'border-top:1px solid #c9d7f1;font-size:1px';
  ExpectedResult := HTML(Format('<span style="%s">%s</span>', [TempStyle, TempString]));
  TestResult := HTMLWriterFactory(cHTML).AddSpanTextWithStyle(TempString, TempStyle).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestTHTMLWriter.TestAddSpanTextWithID;
var
  TempID: string;
  TempString: string;
  TestResult: string;
  ExpectedResult: string;
begin
  TempString := 'flooble';
  TempID := 'main';
  ExpectedResult := HTML(Format('<span id="%s">%s</span>', [TempID, TempString]));
  TestResult := HTMLWriterFactory(cHTML).AddSpanTextWithID(TempString, TempID).CloseTag.AsHTML;
  CheckEquals(ExpectedResult, TestResult);
end;

procedure TestIGetHTML.SetUp;
begin
end;

procedure TestIGetHTML.TearDown;
begin
  FIGetHTML := nil;
end;

procedure TestIGetHTML.TestAsHTML;
var
  ReturnValue: string;
begin
  ReturnValue := FIGetHTML.AsHTML;
end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTHTMLWriter.Suite);

end.
